local nm = require("notmuch.db")
local u = require("test/test/util")

describe("Db tests", function ()
	it("Open db", function ()
		local db = nm.db_open(nil, 0, nil, nil)
	end)
	it("remove message", function ()
		local maildir, db = u.create_db("padd")
    local message = u.insert_email(maildir, db)
		-- db:remove_message(message:filename())
		-- try to get an error finding the file
	end)

	it("get all tags", function ()
		local db = nm.db_open(nil, 0, nil, nil)
    local tags = u.collect(db:get_all_tags())
	end)

	it("reopen and try to write", function ()
		local maildir, db = u.create_db("reopen")
		db:reopen(0)
		db:reopen(1)
	end)
end)
